{
 "title": "nim-dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Time to First Token (TTFT) p50",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(time_to_first_token_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inter-Token Latency (ITL) p50",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(time_per_output_token_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (tok/sec)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(generation_tokens_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Context vs Generated Tokens",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prompt_tokens_total", "legendFormat": "Context Tokens" },
    { "expr": "generation_tokens_total", "legendFormat": "Generated Tokens" }
   ]
  },
  {
   "title": "Prompt Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(request_prompt_tokens_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(request_prompt_tokens_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(request_prompt_tokens_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Generated Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(request_generation_tokens_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(request_generation_tokens_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(request_generation_tokens_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Time to First Token (TTFT)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(time_to_first_token_seconds_bucket[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Inter Token Latency (ITL)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(time_per_output_token_seconds_bucket[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "K/V Cache Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_cache_usage_perc{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "rate(request_success_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Waiting",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_requests_waiting", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_requests_running", "legendFormat": "__auto" }
   ]
  }
 ]
}